"""add Job.text

Revision ID: 89544522fd92
Revises: 210db8286751
Create Date: 2023-04-29 10:26:58.456882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89544522fd92'
down_revision = '210db8286751'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('text', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'text')
    # ### end Alembic commands ###
